version: '3'
services:
        python:
                image: python:3.9.13
                working_dir: /home
                volumes:
                        - $PWD:$VIRTUAL_ENV
                user: $UID:$GID
                environment:
                        - PATH=$VIRTUAL_ENV/venv/bin:$PATH
                        - HOME=$VIRTUAL_ENV
