version: '3'
services:
        python:
                image: python:3.9.13
                working_dir: /home
                volumes:
                        - $PWD:/home
                user: $UID:$GID
