# Generated by Django 4.0.5 on 2022-06-18 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='user_id',
            new_name='user',
        ),
    ]
