# Generated by Django 4.0.5 on 2022-06-30 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_category_user_spending_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='spending',
            name='title',
            field=models.TextField(default='food'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='bot.user'),
        ),
    ]
