# Generated by Django 4.0.5 on 2022-06-30 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_spending_title_alter_category_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spending',
            name='title',
        ),
    ]
